[book]
title = "IoT Stendi Projekt"
authors = ["Disainin värkvõrgu meeskond"]
description = "Juhend IoT stendi projekti läbiviimiseks"
language = "et"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/tluhk/projekt"
edit-url-template = "https://github.com/tluhk/projekt/edit/book/book/{path}"

[output.html.fold]
enable = true
level = 1
